### ISSUE TITLE
Material strength, mass and length adjustments

### ISSUE THREAD

**Issue by Stektpotet** [chordatagames/Bridger#2]
I can only think of one way to get the _right_ values here... A LOT of testing.

| Build> | Test> | if (success)> | if( ! material too weak/short/heavy/strong/long/light) | no? okay :+1: |
| --- | --- | --- | --- | --- |
|  |  | v | v |  |
|  |  | if( ! material too weak/short/heavy/strong/long/light) > | adjust weakest material or mass of strongest  > | Test Again! |

**Comment by solbjorg** [comment]
no? okay :+1:

**Comment by Stektpotet** [comment]
It's waaaaaaay more accurate atm anyways sooooo... yeah :yay: :+1:
